name: arthurdev
description: Personal website and online portfolio for ArthurDev.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_web_plugins:
    sdk: flutter
  http: null
  provider: ^6.0.5
  url_launcher: ^6.1.5
  system_theme: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: SquadaOne
      fonts:
        - asset: assets/fonts/squadaone_regular.ttf
    - family: Righteous
      fonts:
        - asset: assets/fonts/righteous_regular.ttf
    - family: Bree Serif
      fonts:
        - asset: assets/fonts/bree_serif_regular.ttf
    - family: Heebo
      fonts:
        - asset: assets/fonts/heebo_medium.ttf
          weight: 500
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
    - family: MyIcons
      fonts:
        - asset: assets/fonts/my_icons.ttf
