name: Build, Release web app to Github Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.x"
          channel: "beta"
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email arthurdelords@gmail.com
          git config --global user.name thearthurdev
          git status
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/thearthurdev/thearthurdev.github.io.git
          git checkout -b master
          git add --all
          git commit -m "update"
          git push origin master -f
