name: Build, Release web app to Github Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy thearthur.dev
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Upgrade Flutter
        run: flutter upgrade
      - name: Get packages
        run: flutter pub get
#       - name: Enable flutter web
#         run: flutter config --enable-web
      - name: Build web app
        run: flutter build web --release
      - name: Deploy web app
        run: |
          cp CNAME build/web/CNAME
          cd build/web
          git init
          git config --global user.email arthurdelords@gmail.com
          git config --global user.name thearthurdev
          git status
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/thearthurdev/thearthurdev.github.io.git
          git checkout -b master
          git add --all
          git commit -m "${{ github.event.head_commit.message }}"
          git push origin master -f
