name: Build, Release web app to Github Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.x"
          channel: "beta"
      - name: "Upgrade Flutter"
        run: flutter upgrade
      - name: "Run flutter pub get"
        run: flutter pub get
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: "Build Web App"
        run: flutter build web
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build/web
